name: Deploy CookIt Backend

on:
  push:
    branches:
      - deploy-ec2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kabizzle/CookItBackend .

      - name: Publish image to Docker hub
        run: docker push kabizzle/CookItBackend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: docker pull kabizzle/CookItBackend:latest

      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name CookItBackendContainer -e MONGODB_URI='${{secrets.MONGODB_URI}}'' -e JWT_SECRET='${{secrets.JWT_SECRET}}'